name: Squash Commits

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'The commit message for the new, single commit'
        required: true
        default: 'Squashed commits'
      branch:
        description: 'The branch to squash'
        required: true
        default: 'main'

jobs:
  squash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Add files to orphan branch and replace target branch
        run: |
          git checkout --orphan squash-commits-tmp
          git add -A
          git commit -m "${{ github.event.inputs.commit_message }}"
          git branch -D ${{ github.event.inputs.branch }}
          git branch -m ${{ github.event.inputs.branch }}

      - name: Force push to the branch
        run: git push -f origin ${{ github.event.inputs.branch }}
